"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "fr" | "en" | "es" | "de"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Dictionnaire de traductions
const translations = {
  en: {
    // Navigation
    "nav.explore": "Explore",
    "nav.activities": "Activities",
    "nav.messages": "Messages",
    "nav.profile": "Profile",

    // Home Page
    "home.rotating.text1": "Discover unique places",
    "home.rotating.text2": "Plan your next trip",
    "home.rotating.text3": "Share your adventures",
    "home.subtitle": "Your adventure starts here",
    "home.loading": "Preparing your journey...",
    "home.start": "Start the adventure",

    // Auth Page
    "auth.title": "Connect with local guides",
    "auth.traveler": "I'm a traveler",
    "auth.traveler.desc": "I'm looking for a local guide",
    "auth.guide": "I'm a guide",
    "auth.guide.desc": "I offer my services",
    "auth.traveler.space": "Traveler Space",
    "auth.guide.space": "Guide Space",
    "auth.traveler.tagline": "Discover the world with authentic locals",
    "auth.guide.tagline": "Share your passion and local culture",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.login": "Sign in",
    "auth.logging": "Signing in...",
    "auth.no.account": "Don't have an account?",
    "auth.create.account": "Create account",
    "auth.test.accounts": "Test accounts:",
    "auth.admin": "Admin",
    "auth.guide.test": "Guide",
    "auth.traveler.test": "Traveler",

    // Signup Page
    "signup.title": "Join our community of travelers and guides",
    "signup.create.account": "Create your account",
    "signup.email": "Email",
    "signup.password": "Password",
    "signup.password.min": "6 characters minimum",
    "signup.password.help": "Password must contain at least 6 characters",
    "signup.checking": "Checking...",
    "signup.next": "Next",
    "signup.who.are.you": "Who are you?",
    "signup.profile.interests": "Choose your profile and interests",
    "signup.traveler": "I'm a traveler",
    "signup.traveler.desc": "I'm looking for local guides",
    "signup.guide": "I'm a local guide",
    "signup.guide.desc": "I share my culture",
    "signup.interests": "Your interests (minimum 3)",
    "signup.interests.selected": "Selected",
    "signup.interests.none": "No interests selected",
    "signup.finalize": "Finalize your profile",
    "signup.first.name": "First name",
    "signup.last.name": "Last name",
    "signup.preferred.language": "Preferred language",
    "signup.select.language": "Select your language",
    "signup.accept": "I accept the",
    "signup.terms": "terms of use",
    "signup.privacy": "privacy policy",
    "signup.previous": "Previous",
    "signup.finish": "Finish",
    "signup.registering": "Registering...",
    "signup.already.member": "Already a member?",
    "signup.sign.in": "Sign in",
    "signup.error.fill.fields": "Please fill in all fields",
    "signup.error.valid.email": "Please enter a valid email",
    "signup.error.password.length": "Password must contain at least 6 characters",
    "signup.error.email.exists": "An account already exists with this email. Try signing in.",
    "signup.error.verification": "Verification error. Please try again.",
    "signup.error.select.user.type": "Please select a user type",
    "signup.error.min.interests": "Please select at least 3 interests",
    "signup.error.accept.terms": "Please accept the terms of use",
    "signup.error.registration": "Registration error",
    "signup.error.unexpected": "An unexpected error occurred",

    // Onboarding Page
    "onboarding.welcome": "Welcome",
    "onboarding.add.photo": "Let's add a photo so others can recognize you",
    "onboarding.photo.url": "Your photo URL (optional)",
    "onboarding.photo.placeholder": "https://example.com/your-photo.jpg",
    "onboarding.drag.drop": "Or drag and drop an image here",
    "onboarding.location.title": "Where are you based?",
    "onboarding.location.help": "This helps us connect you with local guides and travelers",
    "onboarding.location": "Your location",
    "onboarding.location.placeholder": "Paris, France",
    "onboarding.bio": "Tell us about yourself (optional)",
    "onboarding.bio.placeholder": "I'm passionate about travel and love discovering new cultures...",
    "onboarding.languages.title": "What languages do you speak?",
    "onboarding.languages.help": "Select all languages you master",
    "onboarding.languages.selected": "Selected languages",
    "onboarding.interests.title": "Your interests",
    "onboarding.interests.help": "What excites you most when traveling?",
    "onboarding.interests.selected": "Selected interests",
    "onboarding.travel.style": "Travel style",
    "onboarding.travel.help": "How do you like to travel?",
    "onboarding.style.preferred": "Preferred travel style",
    "onboarding.style.select": "Select your style",
    "onboarding.style.backpacker": "Backpacker / Budget",
    "onboarding.style.comfort": "Comfort / Hotels",
    "onboarding.style.luxury": "Luxury / Premium",
    "onboarding.style.family": "Family travel",
    "onboarding.style.solo": "Solo travel",
    "onboarding.style.group": "Group travel",
    "onboarding.budget": "Approximate daily budget",
    "onboarding.budget.select": "Select your budget",
    "onboarding.budget.low": "Small budget (< $50/day)",
    "onboarding.budget.medium": "Medium budget ($50-150/day)",
    "onboarding.budget.high": "High budget ($150-300/day)",
    "onboarding.budget.luxury": "Luxury budget (> $300/day)",
    "onboarding.almost.done": "Profile almost complete!",
    "onboarding.ready": "You're ready to discover",
    "onboarding.travelers": "travelers",
    "onboarding.guides": "local guides",
    "onboarding.authentic": "and live authentic experiences!",
    "onboarding.step": "Step",
    "onboarding.of": "of",
    "onboarding.complete": "complete",
    "onboarding.previous": "Previous",
    "onboarding.next": "Next",
    "onboarding.finish": "Finish",
    "onboarding.finalizing": "Finalizing...",
    "onboarding.modify.later": "You can modify this information later in your profile",

    // Interest Categories
    "interests.travel.culture": "🌍 Travel & Culture",
    "interests.gastronomy": "🍽️ Gastronomy",
    "interests.sport.adventure": "🏃 Sport & Adventure",
    "interests.arts.creativity": "🎨 Arts & Creativity",
    "interests.nature.wellness": "🌿 Nature & Wellness",
    "interests.learning": "🎓 Learning",
    "interests.social.entertainment": "🎉 Social & Entertainment",

    // Page Explorer
    "explore.title": "Discover the world with local guides",
    "explore.subtitle": "Connect with authentic guides for unique experiences",
    "explore.search.placeholder": "Search for a destination...",
    "explore.search.button": "Search",
    "explore.popular": "Popular destinations",
    "explore.guides": "Recommended guides",
    "explore.rating": "stars",
    "explore.reviews": "reviews",
    "explore.from": "From",
    "explore.per.person": "per person",

    // Page Activités
    "activities.title": "My Activities",
    "activities.upcoming": "Upcoming",
    "activities.past": "Past",
    "activities.with": "with",
    "activities.participants": "participants",
    "activities.modify": "Modify",
    "activities.cancel": "Cancel appointment",
    "activities.cancel.reason": "Cancellation reason (optional)",
    "activities.cancel.confirm": "Confirm cancellation",
    "activities.cancel.success": "Appointment cancelled successfully",

    // Page Messages
    "messages.title": "Messages",
    "messages.search": "Search conversations...",
    "messages.online": "Online",
    "messages.typing": "Typing...",
    "messages.type.message": "Type your message...",
    "messages.send": "Send",

    // Page Profil
    "profile.title": "My Profile",
    "profile.edit": "Edit profile",
    "profile.level": "Level",
    "profile.points": "points",
    "profile.stats.trips": "Trips",
    "profile.stats.guides": "Connected guides",
    "profile.stats.destinations": "Destinations",
    "profile.tabs.overview": "Overview",
    "profile.tabs.trips": "Trips",
    "profile.tabs.achievements": "Achievements",
    "profile.tabs.settings": "Settings",
    "profile.bio": "Biography",
    "profile.languages": "Spoken languages",
    "profile.interests": "Interests",
    "profile.favorites": "Favorite destinations",
    "profile.settings.notifications": "Manage notifications",
    "profile.settings.privacy": "Privacy",
    "profile.settings.language": "Language and region",
    "profile.settings.help": "Help and support",
    "profile.settings.logout": "Sign out",

    // Notifications
    "notifications.title": "Notifications",
    "notifications.push": "Push notifications",
    "notifications.push.enable": "Enable push notifications",
    "notifications.push.test": "Test notifications",
    "notifications.types": "Notification types",
    "notifications.messages": "New messages",
    "notifications.bookings": "Bookings",
    "notifications.promotions": "Promotions",
    "notifications.channels": "Notification channels",
    "notifications.email": "Email",
    "notifications.sms": "SMS",
    "notifications.quiet.hours": "Quiet hours",

    // Privacy
    "privacy.title": "Privacy",
    "privacy.profile.visibility": "Profile visibility",
    "privacy.location": "Location",
    "privacy.messages": "Messages",
    "privacy.data": "Data and analytics",

    // Language
    "language.title": "Language and region",
    "language.app": "App language",
    "language.regional": "Regional format",
    "language.content": "Preferred content languages",
    "language.changing": "Changing language...",
    "language.changed": "Language changed successfully!",

    // Common
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.back": "Back",
    "common.loading": "Loading...",
    "common.error": "An error occurred",
    "common.success": "Success!",
  },
  fr: {
    // Navigation
    "nav.explore": "Explorer",
    "nav.activities": "Activités",
    "nav.messages": "Messages",
    "nav.profile": "Profil",

    // Home Page
    "home.rotating.text1": "Découvrez des lieux uniques",
    "home.rotating.text2": "Planifiez votre prochain voyage",
    "home.rotating.text3": "Partagez vos aventures",
    "home.subtitle": "Votre aventure commence ici",
    "home.loading": "Préparation de votre voyage...",
    "home.start": "Commencer l'aventure",

    // Auth Page
    "auth.title": "Connectez-vous avec des guides locaux",
    "auth.traveler": "Je suis voyageur",
    "auth.traveler.desc": "Je cherche un guide local",
    "auth.guide": "Je suis guide",
    "auth.guide.desc": "Je propose mes services",
    "auth.traveler.space": "Espace Voyageur",
    "auth.guide.space": "Espace Guide",
    "auth.traveler.tagline": "Découvrez le monde avec des locaux authentiques",
    "auth.guide.tagline": "Partagez votre passion et votre culture locale",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.login": "Se connecter",
    "auth.logging": "Connexion...",
    "auth.no.account": "Pas encore de compte ?",
    "auth.create.account": "Créer un compte",
    "auth.test.accounts": "Comptes de test :",
    "auth.admin": "Admin",
    "auth.guide.test": "Guide",
    "auth.traveler.test": "Voyageur",

    // Signup Page
    "signup.title": "Rejoignez notre communauté de voyageurs et guides",
    "signup.create.account": "Créez votre compte",
    "signup.email": "Email",
    "signup.password": "Mot de passe",
    "signup.password.min": "6 caractères minimum",
    "signup.password.help": "Le mot de passe doit contenir au moins 6 caractères",
    "signup.checking": "Vérification...",
    "signup.next": "Suivant",
    "signup.who.are.you": "Qui êtes-vous ?",
    "signup.profile.interests": "Choisissez votre profil et vos centres d'intérêt",
    "signup.traveler": "Je suis voyageur",
    "signup.traveler.desc": "Je cherche des guides locaux",
    "signup.guide": "Je suis guide local",
    "signup.guide.desc": "Je partage ma culture",
    "signup.interests": "Vos centres d'intérêt (minimum 3)",
    "signup.interests.selected": "Sélectionnés",
    "signup.interests.none": "Aucun centre d'intérêt sélectionné",
    "signup.finalize": "Finalisez votre profil",
    "signup.first.name": "Prénom",
    "signup.last.name": "Nom",
    "signup.preferred.language": "Langue préférée",
    "signup.select.language": "Sélectionnez votre langue",
    "signup.accept": "J'accepte les",
    "signup.terms": "conditions d'utilisation",
    "signup.privacy": "politique de confidentialité",
    "signup.previous": "Précédent",
    "signup.finish": "Terminer",
    "signup.registering": "Inscription...",
    "signup.already.member": "Déjà membre ?",
    "signup.sign.in": "Se connecter",
    "signup.error.fill.fields": "Veuillez remplir tous les champs",
    "signup.error.valid.email": "Veuillez entrer un email valide",
    "signup.error.password.length": "Le mot de passe doit contenir au moins 6 caractères",
    "signup.error.email.exists": "Un compte existe déjà avec cet email. Essayez de vous connecter.",
    "signup.error.verification": "Erreur lors de la vérification. Veuillez réessayer.",
    "signup.error.select.user.type": "Veuillez sélectionner un type d'utilisateur",
    "signup.error.min.interests": "Veuillez sélectionner au moins 3 centres d'intérêt",
    "signup.error.accept.terms": "Veuillez accepter les conditions d'utilisation",
    "signup.error.registration": "Erreur d'inscription",
    "signup.error.unexpected": "Une erreur inattendue s'est produite",

    // Onboarding Page
    "onboarding.welcome": "Bienvenue",
    "onboarding.add.photo": "Ajoutons une photo pour que les autres puissent vous reconnaître",
    "onboarding.photo.url": "URL de votre photo (optionnel)",
    "onboarding.photo.placeholder": "https://exemple.com/votre-photo.jpg",
    "onboarding.drag.drop": "Ou glissez-déposez une image ici",
    "onboarding.location.title": "Où êtes-vous basé(e) ?",
    "onboarding.location.help": "Cela nous aide à vous connecter avec des guides et voyageurs locaux",
    "onboarding.location": "Votre localisation",
    "onboarding.location.placeholder": "Paris, France",
    "onboarding.bio": "Parlez-nous de vous (optionnel)",
    "onboarding.bio.placeholder": "Je suis passionné(e) de voyage et j'adore découvrir de nouvelles cultures...",
    "onboarding.languages.title": "Quelles langues parlez-vous ?",
    "onboarding.languages.help": "Sélectionnez toutes les langues que vous maîtrisez",
    "onboarding.languages.selected": "Langues sélectionnées",
    "onboarding.interests.title": "Vos centres d'intérêt",
    "onboarding.interests.help": "Qu'est-ce qui vous passionne le plus en voyage ?",
    "onboarding.interests.selected": "Centres d'intérêt sélectionnés",
    "onboarding.travel.style": "Style de voyage",
    "onboarding.travel.help": "Comment aimez-vous voyager ?",
    "onboarding.style.preferred": "Style de voyage préféré",
    "onboarding.style.select": "Sélectionnez votre style",
    "onboarding.style.backpacker": "Backpacker / Routard",
    "onboarding.style.comfort": "Confort / Hôtels",
    "onboarding.style.luxury": "Luxe / Premium",
    "onboarding.style.family": "Voyage en famille",
    "onboarding.style.solo": "Voyage solo",
    "onboarding.style.group": "Voyage en groupe",
    "onboarding.budget": "Budget approximatif par jour",
    "onboarding.budget.select": "Sélectionnez votre budget",
    "onboarding.budget.low": "Petit budget (< 50€/jour)",
    "onboarding.budget.medium": "Budget moyen (50-150€/jour)",
    "onboarding.budget.high": "Budget élevé (150-300€/jour)",
    "onboarding.budget.luxury": "Budget luxe (> 300€/jour)",
    "onboarding.almost.done": "Profil presque terminé !",
    "onboarding.ready": "Vous êtes prêt(e) à découvrir",
    "onboarding.travelers": "des voyageurs",
    "onboarding.guides": "des guides locaux",
    "onboarding.authentic": "et à vivre des expériences authentiques !",
    "onboarding.step": "Étape",
    "onboarding.of": "sur",
    "onboarding.complete": "terminé",
    "onboarding.previous": "Précédent",
    "onboarding.next": "Suivant",
    "onboarding.finish": "Terminer",
    "onboarding.finalizing": "Finalisation...",
    "onboarding.modify.later": "Vous pourrez modifier ces informations plus tard dans votre profil",

    // Interest Categories
    "interests.travel.culture": "🌍 Voyage & Culture",
    "interests.gastronomy": "🍽️ Gastronomie",
    "interests.sport.adventure": "🏃 Sport & Aventure",
    "interests.arts.creativity": "🎨 Arts & Créativité",
    "interests.nature.wellness": "🌿 Nature & Bien-être",
    "interests.learning": "🎓 Apprentissage",
    "interests.social.entertainment": "🎉 Social & Divertissement",

    // Page Explorer
    "explore.title": "Découvrez le monde avec des guides locaux",
    "explore.subtitle": "Connectez-vous avec des guides authentiques pour des expériences uniques",
    "explore.search.placeholder": "Rechercher une destination...",
    "explore.search.button": "Rechercher",
    "explore.popular": "Destinations populaires",
    "explore.guides": "Guides recommandés",
    "explore.rating": "étoiles",
    "explore.reviews": "avis",
    "explore.from": "À partir de",
    "explore.per.person": "par personne",

    // Page Activités
    "activities.title": "Mes Activités",
    "activities.upcoming": "À venir",
    "activities.past": "Passées",
    "activities.with": "avec",
    "activities.participants": "participants",
    "activities.modify": "Modifier",
    "activities.cancel": "Annuler le rendez-vous",
    "activities.cancel.reason": "Raison de l'annulation (optionnel)",
    "activities.cancel.confirm": "Confirmer l'annulation",
    "activities.cancel.success": "Rendez-vous annulé avec succès",

    // Page Messages
    "messages.title": "Messages",
    "messages.search": "Rechercher dans les conversations...",
    "messages.online": "En ligne",
    "messages.typing": "En train d'écrire...",
    "messages.type.message": "Tapez votre message...",
    "messages.send": "Envoyer",

    // Page Profil
    "profile.title": "Mon Profil",
    "profile.edit": "Modifier le profil",
    "profile.level": "Niveau",
    "profile.points": "points",
    "profile.stats.trips": "Voyages",
    "profile.stats.guides": "Guides connectés",
    "profile.stats.destinations": "Destinations",
    "profile.tabs.overview": "Aperçu",
    "profile.tabs.trips": "Voyages",
    "profile.tabs.achievements": "Succès",
    "profile.tabs.settings": "Paramètres",
    "profile.bio": "Biographie",
    "profile.languages": "Langues parlées",
    "profile.interests": "Centres d'intérêt",
    "profile.favorites": "Destinations favorites",
    "profile.settings.notifications": "Gérer les notifications",
    "profile.settings.privacy": "Confidentialité",
    "profile.settings.language": "Langue et région",
    "profile.settings.help": "Aide et support",
    "profile.settings.logout": "Se déconnecter",

    // Notifications
    "notifications.title": "Notifications",
    "notifications.push": "Notifications push",
    "notifications.push.enable": "Activer les notifications push",
    "notifications.push.test": "Tester les notifications",
    "notifications.types": "Types de notifications",
    "notifications.messages": "Nouveaux messages",
    "notifications.bookings": "Réservations",
    "notifications.promotions": "Promotions",
    "notifications.channels": "Canaux de notification",
    "notifications.email": "Email",
    "notifications.sms": "SMS",
    "notifications.quiet.hours": "Heures silencieuses",

    // Confidentialité
    "privacy.title": "Confidentialité",
    "privacy.profile.visibility": "Visibilité du profil",
    "privacy.location": "Localisation",
    "privacy.messages": "Messages",
    "privacy.data": "Données et analyse",

    // Langue
    "language.title": "Langue et région",
    "language.app": "Langue de l'application",
    "language.regional": "Format régional",
    "language.content": "Langues de contenu préférées",
    "language.changing": "Changement de langue en cours...",
    "language.changed": "Langue changée avec succès !",

    // Commun
    "common.save": "Sauvegarder",
    "common.cancel": "Annuler",
    "common.confirm": "Confirmer",
    "common.back": "Retour",
    "common.loading": "Chargement...",
    "common.error": "Une erreur s'est produite",
    "common.success": "Succès !",
  },
  es: {
    // Navigation
    "nav.explore": "Explorar",
    "nav.activities": "Actividades",
    "nav.messages": "Mensajes",
    "nav.profile": "Perfil",

    // Home Page
    "home.rotating.text1": "Descubre lugares únicos",
    "home.rotating.text2": "Planifica tu próximo viaje",
    "home.rotating.text3": "Comparte tus aventuras",
    "home.subtitle": "Tu aventura comienza aquí",
    "home.loading": "Preparando tu viaje...",
    "home.start": "Comenzar la aventura",

    // Auth Page
    "auth.title": "Conéctate con guías locales",
    "auth.traveler": "Soy viajero",
    "auth.traveler.desc": "Busco un guía local",
    "auth.guide": "Soy guía",
    "auth.guide.desc": "Ofrezco mis servicios",
    "auth.traveler.space": "Espacio Viajero",
    "auth.guide.space": "Espacio Guía",
    "auth.traveler.tagline": "Descubre el mundo con locales auténticos",
    "auth.guide.tagline": "Comparte tu pasión y cultura local",
    "auth.email": "Email",
    "auth.password": "Contraseña",
    "auth.login": "Iniciar sesión",
    "auth.logging": "Iniciando sesión...",
    "auth.no.account": "¿No tienes cuenta?",
    "auth.create.account": "Crear cuenta",
    "auth.test.accounts": "Cuentas de prueba:",
    "auth.admin": "Admin",
    "auth.guide.test": "Guía",
    "auth.traveler.test": "Viajero",

    // Signup Page
    "signup.title": "Únete a nuestra comunidad de viajeros y guías",
    "signup.create.account": "Crea tu cuenta",
    "signup.email": "Email",
    "signup.password": "Contraseña",
    "signup.password.min": "6 caracteres mínimo",
    "signup.password.help": "La contraseña debe contener al menos 6 caracteres",
    "signup.checking": "Verificando...",
    "signup.next": "Siguiente",
    "signup.who.are.you": "¿Quién eres?",
    "signup.profile.interests": "Elige tu perfil e intereses",
    "signup.traveler": "Soy viajero",
    "signup.traveler.desc": "Busco guías locales",
    "signup.guide": "Soy guía local",
    "signup.guide.desc": "Comparto mi cultura",
    "signup.interests": "Tus intereses (mínimo 3)",
    "signup.interests.selected": "Seleccionados",
    "signup.interests.none": "Ningún interés seleccionado",
    "signup.finalize": "Finaliza tu perfil",
    "signup.first.name": "Nombre",
    "signup.last.name": "Apellido",
    "signup.preferred.language": "Idioma preferido",
    "signup.select.language": "Selecciona tu idioma",
    "signup.accept": "Acepto los",
    "signup.terms": "términos de uso",
    "signup.privacy": "política de privacidad",
    "signup.previous": "Anterior",
    "signup.finish": "Terminar",
    "signup.registering": "Registrando...",
    "signup.already.member": "¿Ya eres miembro?",
    "signup.sign.in": "Iniciar sesión",
    "signup.error.fill.fields": "Por favor completa todos los campos",
    "signup.error.valid.email": "Por favor ingresa un email válido",
    "signup.error.password.length": "La contraseña debe contener al menos 6 caracteres",
    "signup.error.email.exists": "Ya existe una cuenta con este email. Intenta iniciar sesión.",
    "signup.error.verification": "Error de verificación. Por favor intenta de nuevo.",
    "signup.error.select.user.type": "Por favor selecciona un tipo de usuario",
    "signup.error.min.interests": "Por favor selecciona al menos 3 intereses",
    "signup.error.accept.terms": "Por favor acepta los términos de uso",
    "signup.error.registration": "Error de registro",
    "signup.error.unexpected": "Ocurrió un error inesperado",

    // Onboarding Page
    "onboarding.welcome": "Bienvenido",
    "onboarding.add.photo": "Agreguemos una foto para que otros puedan reconocerte",
    "onboarding.photo.url": "URL de tu foto (opcional)",
    "onboarding.photo.placeholder": "https://ejemplo.com/tu-foto.jpg",
    "onboarding.drag.drop": "O arrastra y suelta una imagen aquí",
    "onboarding.location.title": "¿Dónde te encuentras?",
    "onboarding.location.help": "Esto nos ayuda a conectarte con guías y viajeros locales",
    "onboarding.location": "Tu ubicación",
    "onboarding.location.placeholder": "Madrid, España",
    "onboarding.bio": "Cuéntanos sobre ti (opcional)",
    "onboarding.bio.placeholder": "Soy apasionado de los viajes y me encanta descubrir nuevas culturas...",
    "onboarding.languages.title": "¿Qué idiomas hablas?",
    "onboarding.languages.help": "Selecciona todos los idiomas que dominas",
    "onboarding.languages.selected": "Idiomas seleccionados",
    "onboarding.interests.title": "Tus intereses",
    "onboarding.interests.help": "¿Qué te emociona más al viajar?",
    "onboarding.interests.selected": "Intereses seleccionados",
    "onboarding.travel.style": "Estilo de viaje",
    "onboarding.travel.help": "¿Cómo te gusta viajar?",
    "onboarding.style.preferred": "Estilo de viaje preferido",
    "onboarding.style.select": "Selecciona tu estilo",
    "onboarding.style.backpacker": "Mochilero / Económico",
    "onboarding.style.comfort": "Confort / Hoteles",
    "onboarding.style.luxury": "Lujo / Premium",
    "onboarding.style.family": "Viaje familiar",
    "onboarding.style.solo": "Viaje solo",
    "onboarding.style.group": "Viaje en grupo",
    "onboarding.budget": "Presupuesto diario aproximado",
    "onboarding.budget.select": "Selecciona tu presupuesto",
    "onboarding.budget.low": "Presupuesto bajo (< $50/día)",
    "onboarding.budget.medium": "Presupuesto medio ($50-150/día)",
    "onboarding.budget.high": "Presupuesto alto ($150-300/día)",
    "onboarding.budget.luxury": "Presupuesto de lujo (> $300/día)",
    "onboarding.almost.done": "¡Perfil casi completo!",
    "onboarding.ready": "Estás listo para descubrir",
    "onboarding.travelers": "viajeros",
    "onboarding.guides": "guías locales",
    "onboarding.authentic": "y vivir experiencias auténticas!",
    "onboarding.step": "Paso",
    "onboarding.of": "de",
    "onboarding.complete": "completo",
    "onboarding.previous": "Anterior",
    "onboarding.next": "Siguiente",
    "onboarding.finish": "Terminar",
    "onboarding.finalizing": "Finalizando...",
    "onboarding.modify.later": "Puedes modificar esta información más tarde en tu perfil",

    // Interest Categories
    "interests.travel.culture": "🌍 Viaje y Cultura",
    "interests.gastronomy": "🍽️ Gastronomía",
    "interests.sport.adventure": "🏃 Deporte y Aventura",
    "interests.arts.creativity": "🎨 Arte y Creatividad",
    "interests.nature.wellness": "🌿 Naturaleza y Bienestar",
    "interests.learning": "🎓 Aprendizaje",
    "interests.social.entertainment": "🎉 Social y Entretenimiento",

    // Page Explorer
    "explore.title": "Descubre el mundo con guías locales",
    "explore.subtitle": "Conéctate con guías auténticos para experiencias únicas",
    "explore.search.placeholder": "Buscar un destino...",
    "explore.search.button": "Buscar",
    "explore.popular": "Destinos populares",
    "explore.guides": "Guías recomendados",
    "explore.rating": "estrellas",
    "explore.reviews": "reseñas",
    "explore.from": "Desde",
    "explore.per.person": "por persona",

    // Page Activités
    "activities.title": "Mis Actividades",
    "activities.upcoming": "Próximas",
    "activities.past": "Pasadas",
    "activities.with": "con",
    "activities.participants": "participantes",
    "activities.modify": "Modificar",
    "activities.cancel": "Cancelar cita",
    "activities.cancel.reason": "Razón de cancelación (opcional)",
    "activities.cancel.confirm": "Confirmar cancelación",
    "activities.cancel.success": "Cita cancelada exitosamente",

    // Page Messages
    "messages.title": "Mensajes",
    "messages.search": "Buscar conversaciones...",
    "messages.online": "En línea",
    "messages.typing": "Escribiendo...",
    "messages.type.message": "Escribe tu mensaje...",
    "messages.send": "Enviar",

    // Page Profil
    "profile.title": "Mi Perfil",
    "profile.edit": "Editar perfil",
    "profile.level": "Nivel",
    "profile.points": "puntos",
    "profile.stats.trips": "Viajes",
    "profile.stats.guides": "Guías conectados",
    "profile.stats.destinations": "Destinos",
    "profile.tabs.overview": "Resumen",
    "profile.tabs.trips": "Viajes",
    "profile.tabs.achievements": "Logros",
    "profile.tabs.settings": "Configuración",
    "profile.bio": "Biografía",
    "profile.languages": "Idiomas hablados",
    "profile.interests": "Intereses",
    "profile.favorites": "Destinos favoritos",
    "profile.settings.notifications": "Gestionar notificaciones",
    "profile.settings.privacy": "Privacidad",
    "profile.settings.language": "Idioma y región",
    "profile.settings.help": "Ayuda y soporte",
    "profile.settings.logout": "Cerrar sesión",

    // Notifications
    "notifications.title": "Notificaciones",
    "notifications.push": "Notificaciones push",
    "notifications.push.enable": "Activar notificaciones push",
    "notifications.push.test": "Probar notificaciones",
    "notifications.types": "Tipos de notificaciones",
    "notifications.messages": "Nuevos mensajes",
    "notifications.bookings": "Reservas",
    "notifications.promotions": "Promociones",
    "notifications.channels": "Canales de notificación",
    "notifications.email": "Email",
    "notifications.sms": "SMS",
    "notifications.quiet.hours": "Horas silenciosas",

    // Confidentialité
    "privacy.title": "Privacidad",
    "privacy.profile.visibility": "Visibilidad del perfil",
    "privacy.location": "Ubicación",
    "privacy.messages": "Mensajes",
    "privacy.data": "Datos y análisis",

    // Langue
    "language.title": "Idioma y región",
    "language.app": "Idioma de la aplicación",
    "language.regional": "Formato regional",
    "language.content": "Idiomas de contenido preferidos",
    "language.changing": "Cambiando idioma...",
    "language.changed": "¡Idioma cambiado exitosamente!",

    // Commun
    "common.save": "Guardar",
    "common.cancel": "Cancelar",
    "common.confirm": "Confirmar",
    "common.back": "Volver",
    "common.loading": "Cargando...",
    "common.error": "Ocurrió un error",
    "common.success": "¡Éxito!",
  },
  de: {
    // Navigation
    "nav.explore": "Entdecken",
    "nav.activities": "Aktivitäten",
    "nav.messages": "Nachrichten",
    "nav.profile": "Profil",

    // Home Page
    "home.rotating.text1": "Entdecke einzigartige Orte",
    "home.rotating.text2": "Plane deine nächste Reise",
    "home.rotating.text3": "Teile deine Abenteuer",
    "home.subtitle": "Dein Abenteuer beginnt hier",
    "home.loading": "Bereite deine Reise vor...",
    "home.start": "Abenteuer starten",

    // Auth Page
    "auth.title": "Verbinde dich mit lokalen Guides",
    "auth.traveler": "Ich bin Reisender",
    "auth.traveler.desc": "Ich suche einen lokalen Guide",
    "auth.guide": "Ich bin Guide",
    "auth.guide.desc": "Ich biete meine Dienste an",
    "auth.traveler.space": "Reisenden-Bereich",
    "auth.guide.space": "Guide-Bereich",
    "auth.traveler.tagline": "Entdecke die Welt mit authentischen Einheimischen",
    "auth.guide.tagline": "Teile deine Leidenschaft und lokale Kultur",
    "auth.email": "E-Mail",
    "auth.password": "Passwort",
    "auth.login": "Anmelden",
    "auth.logging": "Anmeldung...",
    "auth.no.account": "Noch kein Konto?",
    "auth.create.account": "Konto erstellen",
    "auth.test.accounts": "Test-Konten:",
    "auth.admin": "Admin",
    "auth.guide.test": "Guide",
    "auth.traveler.test": "Reisender",

    // Signup Page
    "signup.title": "Tritt unserer Gemeinschaft von Reisenden und Guides bei",
    "signup.create.account": "Erstelle dein Konto",
    "signup.email": "E-Mail",
    "signup.password": "Passwort",
    "signup.password.min": "6 Zeichen minimum",
    "signup.password.help": "Das Passwort muss mindestens 6 Zeichen enthalten",
    "signup.checking": "Überprüfung...",
    "signup.next": "Weiter",
    "signup.who.are.you": "Wer bist du?",
    "signup.profile.interests": "Wähle dein Profil und Interessen",
    "signup.traveler": "Ich bin Reisender",
    "signup.traveler.desc": "Ich suche lokale Guides",
    "signup.guide": "Ich bin lokaler Guide",
    "signup.guide.desc": "Ich teile meine Kultur",
    "signup.interests": "Deine Interessen (mindestens 3)",
    "signup.interests.selected": "Ausgewählt",
    "signup.interests.none": "Keine Interessen ausgewählt",
    "signup.finalize": "Finalisiere dein Profil",
    "signup.first.name": "Vorname",
    "signup.last.name": "Nachname",
    "signup.preferred.language": "Bevorzugte Sprache",
    "signup.select.language": "Wähle deine Sprache",
    "signup.accept": "Ich akzeptiere die",
    "signup.terms": "Nutzungsbedingungen",
    "signup.privacy": "Datenschutzrichtlinie",
    "signup.previous": "Zurück",
    "signup.finish": "Beenden",
    "signup.registering": "Registrierung...",
    "signup.already.member": "Bereits Mitglied?",
    "signup.sign.in": "Anmelden",
    "signup.error.fill.fields": "Bitte fülle alle Felder aus",
    "signup.error.valid.email": "Bitte gib eine gültige E-Mail ein",
    "signup.error.password.length": "Das Passwort muss mindestens 6 Zeichen enthalten",
    "signup.error.email.exists": "Ein Konto mit dieser E-Mail existiert bereits. Versuche dich anzumelden.",
    "signup.error.verification": "Überprüfungsfehler. Bitte versuche es erneut.",
    "signup.error.select.user.type": "Bitte wähle einen Benutzertyp",
    "signup.error.min.interests": "Bitte wähle mindestens 3 Interessen",
    "signup.error.accept.terms": "Bitte akzeptiere die Nutzungsbedingungen",
    "signup.error.registration": "Registrierungsfehler",
    "signup.error.unexpected": "Ein unerwarteter Fehler ist aufgetreten",

    // Onboarding Page
    "onboarding.welcome": "Willkommen",
    "onboarding.add.photo": "Lass uns ein Foto hinzufügen, damit andere dich erkennen können",
    "onboarding.photo.url": "Deine Foto-URL (optional)",
    "onboarding.photo.placeholder": "https://beispiel.com/dein-foto.jpg",
    "onboarding.drag.drop": "Oder ziehe ein Bild hierher",
    "onboarding.location.title": "Wo bist du ansässig?",
    "onboarding.location.help": "Das hilft uns, dich mit lokalen Guides und Reisenden zu verbinden",
    "onboarding.location": "Dein Standort",
    "onboarding.location.placeholder": "Berlin, Deutschland",
    "onboarding.bio": "Erzähle uns von dir (optional)",
    "onboarding.bio.placeholder": "Ich bin leidenschaftlich am Reisen und liebe es, neue Kulturen zu entdecken...",
    "onboarding.languages.title": "Welche Sprachen sprichst du?",
    "onboarding.languages.help": "Wähle alle Sprachen, die du beherrschst",
    "onboarding.languages.selected": "Ausgewählte Sprachen",
    "onboarding.interests.title": "Deine Interessen",
    "onboarding.interests.help": "Was begeistert dich am meisten beim Reisen?",
    "onboarding.interests.selected": "Ausgewählte Interessen",
    "onboarding.travel.style": "Reisestil",
    "onboarding.travel.help": "Wie reist du gerne?",
    "onboarding.style.preferred": "Bevorzugter Reisestil",
    "onboarding.style.select": "Wähle deinen Stil",
    "onboarding.style.backpacker": "Backpacker / Budget",
    "onboarding.style.comfort": "Komfort / Hotels",
    "onboarding.style.luxury": "Luxus / Premium",
    "onboarding.style.family": "Familienreise",
    "onboarding.style.solo": "Alleinreise",
    "onboarding.style.group": "Gruppenreise",
    "onboarding.budget": "Ungefähres Tagesbudget",
    "onboarding.budget.select": "Wähle dein Budget",
    "onboarding.budget.low": "Kleines Budget (< 50€/Tag)",
    "onboarding.budget.medium": "Mittleres Budget (50-150€/Tag)",
    "onboarding.budget.high": "Hohes Budget (150-300€/Tag)",
    "onboarding.budget.luxury": "Luxus-Budget (> 300€/Tag)",
    "onboarding.almost.done": "Profil fast fertig!",
    "onboarding.ready": "Du bist bereit zu entdecken",
    "onboarding.travelers": "Reisende",
    "onboarding.guides": "lokale Guides",
    "onboarding.authentic": "und authentische Erfahrungen zu leben!",
    "onboarding.step": "Schritt",
    "onboarding.of": "von",
    "onboarding.complete": "abgeschlossen",
    "onboarding.previous": "Zurück",
    "onboarding.next": "Weiter",
    "onboarding.finish": "Beenden",
    "onboarding.finalizing": "Finalisierung...",
    "onboarding.modify.later": "Du kannst diese Informationen später in deinem Profil ändern",

    // Interest Categories
    "interests.travel.culture": "🌍 Reise & Kultur",
    "interests.gastronomy": "🍽️ Gastronomie",
    "interests.sport.adventure": "🏃 Sport & Abenteuer",
    "interests.arts.creativity": "🎨 Kunst & Kreativität",
    "interests.nature.wellness": "🌿 Natur & Wellness",
    "interests.learning": "🎓 Lernen",
    "interests.social.entertainment": "🎉 Soziales & Unterhaltung",

    // Page Explorer
    "explore.title": "Entdecke die Welt mit lokalen Guides",
    "explore.subtitle": "Verbinde dich mit authentischen Guides für einzigartige Erfahrungen",
    "explore.search.placeholder": "Nach einem Ziel suchen...",
    "explore.search.button": "Suchen",
    "explore.popular": "Beliebte Ziele",
    "explore.guides": "Empfohlene Guides",
    "explore.rating": "Sterne",
    "explore.reviews": "Bewertungen",
    "explore.from": "Ab",
    "explore.per.person": "pro Person",

    // Page Activités
    "activities.title": "Meine Aktivitäten",
    "activities.upcoming": "Bevorstehend",
    "activities.past": "Vergangen",
    "activities.with": "mit",
    "activities.participants": "Teilnehmer",
    "activities.modify": "Ändern",
    "activities.cancel": "Termin absagen",
    "activities.cancel.reason": "Grund für Absage (optional)",
    "activities.cancel.confirm": "Absage bestätigen",
    "activities.cancel.success": "Termin erfolgreich abgesagt",

    // Page Messages
    "messages.title": "Nachrichten",
    "messages.search": "Unterhaltungen durchsuchen...",
    "messages.online": "Online",
    "messages.typing": "Tippt...",
    "messages.type.message": "Nachricht eingeben...",
    "messages.send": "Senden",

    // Page Profil
    "profile.title": "Mein Profil",
    "profile.edit": "Profil bearbeiten",
    "profile.level": "Level",
    "profile.points": "Punkte",
    "profile.stats.trips": "Reisen",
    "profile.stats.guides": "Verbundene Guides",
    "profile.stats.destinations": "Ziele",
    "profile.tabs.overview": "Übersicht",
    "profile.tabs.trips": "Reisen",
    "profile.tabs.achievements": "Erfolge",
    "profile.tabs.settings": "Einstellungen",
    "profile.bio": "Biografie",
    "profile.languages": "Gesprochene Sprachen",
    "profile.interests": "Interessen",
    "profile.favorites": "Lieblingsziele",
    "profile.settings.notifications": "Benachrichtigungen verwalten",
    "profile.settings.privacy": "Datenschutz",
    "profile.settings.language": "Sprache und Region",
    "profile.settings.help": "Hilfe und Support",
    "profile.settings.logout": "Abmelden",

    // Notifications
    "notifications.title": "Benachrichtigungen",
    "notifications.push": "Push-Benachrichtigungen",
    "notifications.push.enable": "Push-Benachrichtigungen aktivieren",
    "notifications.push.test": "Benachrichtigungen testen",
    "notifications.types": "Benachrichtigungstypen",
    "notifications.messages": "Neue Nachrichten",
    "notifications.bookings": "Buchungen",
    "notifications.promotions": "Aktionen",
    "notifications.channels": "Benachrichtigungskanäle",
    "notifications.email": "E-Mail",
    "notifications.sms": "SMS",
    "notifications.quiet.hours": "Ruhezeiten",

    // Confidentialité
    "privacy.title": "Datenschutz",
    "privacy.profile.visibility": "Profilsichtbarkeit",
    "privacy.location": "Standort",
    "privacy.messages": "Nachrichten",
    "privacy.data": "Daten und Analyse",

    // Langue
    "language.title": "Sprache und Region",
    "language.app": "App-Sprache",
    "language.regional": "Regionales Format",
    "language.content": "Bevorzugte Inhaltssprachen",
    "language.changing": "Sprache wird geändert...",
    "language.changed": "Sprache erfolgreich geändert!",

    // Commun
    "common.save": "Speichern",
    "common.cancel": "Abbrechen",
    "common.confirm": "Bestätigen",
    "common.back": "Zurück",
    "common.loading": "Laden...",
    "common.error": "Ein Fehler ist aufgetreten",
    "common.success": "Erfolg!",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en")

  // Charger la langue depuis le localStorage au démarrage
  useEffect(() => {
    const savedLanguage = localStorage.getItem("tripers-language") as Language
    if (savedLanguage && translations[savedLanguage]) {
      setLanguageState(savedLanguage)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("tripers-language", lang)
  }

  const t = (key: string): string => {
    const translation = translations[language]?.[key]
    if (!translation) {
      // Retourner la traduction anglaise par défaut si elle existe
      return translations.en[key] || key
    }
    return translation
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
